### ISSUE TITLE
Chrome, Insecure Content Blocked

### ISSUE THREAD

**Issue by XxROBOTICSxX** [TGRHavoc/live_map-interface#13]
When accessing the interface via chrome, use must click security warning icon on URL bar and then click "Load unsafe scripts" without doing this the interface cannot connect with the FiveM resource and will not function.

**Comment by davwheat** [comment]
That only occurs if the resources are hosted on a secure (Https) website.

**Comment by TGRHavoc** [comment]
Like @davwheat said, this only happens when loading the interface over HTTPS.

This is because the sockets don't support TLS connections. I know how to implement it and, it's relatively easy to do. The only problem is that the implementation of Mono that FiveM uses doesn't have the X509Certificate2 class implemented (this is the certificate class the websockets use) so, it's useless. 

I will look into other solutions (may this be using another socket library or re-compiling the one I'm using) because I do want to implement TLS connections (I wanted to do this when I started, if you look at earlier commits).

**Comment by XxROBOTICSxX** [comment]
Alright, for the time being our users will have to click "Load Unsafe Scripts" as our current web hosting environment does not allow us to run any of our services over a non secure (HTTPS) connection.
