### ISSUE TITLE
Migrate from Google Maps API to an open source alternative

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map-interface#20]
As of right now, the map is usable but certain features are disabled due to Google's crack down on keyless use of their APIs.

So, instead of making people (potentially) pay money to Google just to use the map, I want to migrate to a (preferably) open source alternative.

I've had a look around and at the moment, [OpenLayers](http://openlayers.org/) seems like the best alternative.

**Comment by JasonO99** [comment]
https://leafletjs.com/

Is this any good or not quite the thing you're looking for?

**Comment by davwheat** [comment]
That actually looks really good and performs well on my devices compared to
Google's Dynamic Maps

**Comment by JasonO99** [comment]
It has an option where you can use a single mapping image, avoids having to create tiles. For the simplicity of a 2d map that's probably good enough. You can then set your own coordinate range from corner to corner. All that in about 2 lines.

**Comment by davwheat** [comment]
That makes it waaay more simple! The issue is, do you go for a very high
resolution image which might take a long time to load or a low resolution
image that will load faster but look worse.

On 17 Nov 2018 15:37, "Jason Olsen" <notifications@github.com> wrote:

It has an option where you can use a single mapping image, avoids having to
create tiles. For the simplicity of a 2d map that's probably good enough.
You can then set your own coordinate range from corner to corner. All that
in about 2 lines.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/TGRHavoc/live_map-interface/issues/20#issuecomment-439625892>,
or mute the thread

**Comment by matsn0w** [comment]
@davwheat tested an 2K pic which loaded quite good, so it will probably be fine

**Comment by davwheat** [comment]
I'll try to convert the map over then

On 17 Nov 2018 15:45, "matsn0w" <notifications@github.com> wrote:

@davwheat <https://github.com/davwheat> tested an 2K pic which loaded quite
good, so it will probably be fine

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/TGRHavoc/live_map-interface/issues/20#issuecomment-439626438>,
or mute the thread

**Comment by JasonO99** [comment]
It's worth noting the tile option is still available too, should that be preferred.

**Comment by JasonO99** [comment]
Regarding 2 lines. I fibbed - but it's no more than 5 for basic custom, single image, map layer.

```
var map = L.map('map', {
    crs: L.CRS.Simple
});
var bounds = [[0,0], [1000,1000]];
var image = L.imageOverlay('uqm_map_full.png', bounds).addTo(map);
map.fitBounds(bounds);
```
Source: https://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by davwheat** [comment]
I found that it's easier to use tiles as that's how the current map works.

On 17 Nov 2018 17:38, "Jason Olsen" <notifications@github.com> wrote:

Regarding 2 lines. I fibbed - but it's no more than 5 for basic custom,
single image, map layer.

var map = L.map('map', {
    crs: L.CRS.Simple
});
var bounds = [[0,0], [1000,1000]];
var image = L.imageOverlay('uqm_map_full.png', bounds).addTo(map);
map.fitBounds(bounds);

Source: https://leafletjs.com/examples/crs-simple/crs-simple.html

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/TGRHavoc/live_map-interface/issues/20#issuecomment-439634054>,
or mute the thread

**Comment by matsn0w** [comment]
Awesome!

**Comment by davwheat** [comment]
![image](https://user-images.githubusercontent.com/7406822/51139850-e0cac400-183c-11e9-9ec1-9479c86db1da.png)

How pleasant.

**Comment by Starystars67** [comment]
Nice work sir! Glad to see this is not a dead project!

**Comment by TGRHavoc** [comment]
Guys, if you want to test the new framework and stuff before I release it to everyone (want to get the other features done first) then, I'd check out the development branch. The new map should be working as of 163a39af58a063edbdb31c8d0dbd1853a636573c.

The new tile image location are hard-coded into `js/src/map.js` (lines 24 and 25) at the minute. That will change in the future, and use the config's location.

The images can be extracted by yourselves. Just extract the PNG files from the YTD files inside GTA with OpenIV. Or, extract them from the YTD files for the custom maps. I highly suggest you use the `minimap_sea` files as they're a higher resolution than the normal `minimap` files.

If you're too lazy to extract yourself, I have a ZIP file containing the images used in the previous comment. It's attached to this comment as "tiles.zip".

[tiles.zip](https://tgrhavoc.me/fuck_you/downloads/tiles.zip)
