### ISSUE TITLE
Players Duplicating in list and sometimes on map

### ISSUE THREAD

**Issue by JasonO99** [TGRHavoc/live_map-interface#33]
https://i.gyazo.com/dcb5bf8cb3bd3f69ca64538188cb6620.png
https://i.gyazo.com/609c241321dffc4a9792f2f150f4b386.png

The list of players is occasionally populating numerous times with the same player. Refreshing the page fixes this. Unable to do anything to reproduce at the moment. Just load the page and after some time (anything from a minute to 15 minutes) I will notice this. The player count also appears incorrect at times to what it actually is (eg in image 2 it shows 3 players, when in fact there is only two - confirmed by looking at players.json on the FiveM server).

Also, sometimes when this happens the marker duplicates (with one being frozen, while the other is moving with the player). It doesn't happen all the time. Also, some players no longer on the server remain on the map.
https://i.gyazo.com/d171ec53a45f9f16137eeb2a3f53fba1.png

I'm running the latest version of Chrome and on Windows 10. Let me know if there's anything else I can offer/look at to help you figure out the issue?

**Comment by JasonO99** [comment]
Uploaded. Will test tonight.

**Comment by JasonO99** [comment]
@TGRHavoc 
http://kentroleplay.co.uk/map2/
Still getting the issue of duplication. Just remain on the page and wait a while. This will only really be busy 1930 - 2130.

**Comment by TGRHavoc** [comment]
~~Hmm. I'm not able to reproduce the errors you're having, The only thing that I can think of is that somehow the player's identifiers are changing from the values originally sent to the map somehow. And that just seems like something that shouldn't happen (I'm basically grasping at straws to try and come up with an idea as to why it's breaking).~~

~~The only thing I can do is ask for some more data to try and pinpoint the issue.
VPS OS - some people have reported the resource not working properly on Linux. May be causing some issues here too, maybe I'm not keeping the interface open long enough to see the server somehow changing stuff it sends.
Browser - It could be a browser issue. Somehow~~

Ok. So, whilst writing this report, I've manage to capture the issue you're having... By the looks of it, the server is picking up that the player is on it but, not sending the identifier of the server. Since the interface relies on that being set in the player options (and in a cache, used for creating markers) it could be causing issues.

![](https://tgrhavoc.me/fuck_you/slut/t1OGceD2uyNatAIpOHtghJywk.png)

You're not by any chase using OneSync are you?

**Comment by JasonO99** [comment]
Not using OneSync. Linux server using the latest build (on Zap Hosting).

**Comment by JasonO99** [comment]
I've updated the code on that last commit. Will look to check this when we have our next burst of players (1930 UK time).

**Comment by JasonO99** [comment]
Unfortunately, the issue is still occurring.

https://i.gyazo.com/3cb7816c8d4f6fff179c76a4b05e9f66.png

**Comment by TGRHavoc** [comment]
> Unfortunately, the issue is still occurring.
> 
> https://i.gyazo.com/3cb7816c8d4f6fff179c76a4b05e9f66.png

You did download the `dist/` folder, right? That's what contains the JS for the main page. Otherwise, only the `debug.html` file will have the changes (I say this because I can't find the added line in `first-bundle.js`).

**Comment by JasonO99** [comment]
I thought I did. I've downloaded it again, deleted all files except images and reuploaded. Config redone. Will test again in 17 hours time.

**Comment by JasonO99** [comment]
I've uploaded the development branch completely. Still doing it.

http://kentroleplay.co.uk/map2/

**Comment by TGRHavoc** [comment]
I'm a fucking moron. Should work as 5cf85131d597be810330270b1bf3ac3344f31c23

**Comment by JasonO99** [comment]
Is that the only file change?

**Comment by TGRHavoc** [comment]
Yea.

**Comment by JasonO99** [comment]
Uploaded. Will update you again.

**Comment by JasonO99** [comment]
Been on 30 minutes. The issue would have certainly appeared by now but has not done so; so appears issue is fixed.
