### ISSUE TITLE
Interface select automatic the system language.

### ISSUE THREAD

**Issue by Mailootje** [TGRHavoc/live_map-interface#74]
The interface will automatically select the system language for no reason. This bugs the interface and will not connect to the resource in the server. Can I manually set the standard language and lock it?

Kind regards,

Mailootje

https://github.com/TGRHavoc/live_map-interface

**Comment by TGRHavoc** [comment]
I mean, it selects your system language to try and provide a nice experience to the user,being greeted by a language they know well rather than something they might not know.

What do you mean by it bugs the interface? Does it not load, does it give any errors?

Maybe its because the language file doesn't exist and its looking for it, would you prefer the interface to default to English if it cannot find a file for your preferred language?
